/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Gebel
 */
public class galeriaTAP extends javax.swing.JFrame /*implements Runnable*/ {

    /**
     * Creates new form galeriaTAP
     */
    ArrayList<File> aux = new ArrayList();

    musicaTest p1;
    serieDos p2;
    serieTres p3;
    serieCuatro p4;
    fileInstancia auxiImg, auxiIniciante;
    public static long duracionPaus = 0;
    public static boolean ejecutando;
    boolean band = false;
    public static AudioInputStream audioInputStream;
    public static Clip clip;

    public galeriaTAP() {
        initComponents();
        btnUno.setEnabled(false);
        //btnUno.setSelected(true);//////////
        btnDos.setEnabled(false);
        btnTres.setEnabled(false);
        btnCuatro.setEnabled(false);
        btnIniciar.setEnabled(false);
        btnBocina.setEnabled(false);
        ejecutando = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGaleria = new javax.swing.JLabel();
        btnUno = new javax.swing.JRadioButton();
        btnDos = new javax.swing.JRadioButton();
        btnTres = new javax.swing.JRadioButton();
        btnCuatro = new javax.swing.JRadioButton();
        btnLeer = new javax.swing.JButton();
        btnIniciar = new javax.swing.JButton();
        btnBocina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUno.setText("1X");
        btnUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnoActionPerformed(evt);
            }
        });

        btnDos.setText("2X");
        btnDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosActionPerformed(evt);
            }
        });

        btnTres.setText("3X");
        btnTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTresActionPerformed(evt);
            }
        });

        btnCuatro.setText("4X");
        btnCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuatroActionPerformed(evt);
            }
        });

        btnLeer.setText("Leer imagenes");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnBocina.setText("▶");
        btnBocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBocinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLeer)
                        .addGap(161, 161, 161)
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBocina, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUno)
                        .addGap(140, 140, 140)
                        .addComponent(btnDos)
                        .addGap(178, 178, 178)
                        .addComponent(btnTres)
                        .addGap(138, 138, 138)
                        .addComponent(btnCuatro)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(lblGaleria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUno)
                    .addComponent(btnDos)
                    .addComponent(btnTres)
                    .addComponent(btnCuatro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeer)
                    .addComponent(btnIniciar)
                    .addComponent(btnBocina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnoActionPerformed
        btnDos.setSelected(false);
        btnTres.setSelected(false);
        btnCuatro.setSelected(false);
        if (ejecutando == true && btnUno.isSelected() == true) {
            p2.detener();
            p3.detener();
            p4.detener();
            p1.start();
        } else if (ejecutando == true && btnUno.isSelected() == false) {
            p1.detener();
            JOptionPane.showMessageDialog(rootPane, "desmarcó en tiempo de ejecución, seleccione una velocidad");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Velocidad seleccionada, presione iniciar");
        }
    }//GEN-LAST:event_btnUnoActionPerformed

    private void btnDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosActionPerformed
        btnUno.setSelected(false);
        btnTres.setSelected(false);
        btnCuatro.setSelected(false);
        if (ejecutando == true && btnDos.isSelected() == true) {
            p1.detener();
            p3.detener();
            p4.detener();
            p2.start();
        } else if (ejecutando == true && btnDos.isSelected() == false) {
            p2.detener();
            JOptionPane.showMessageDialog(rootPane, "desmarcó en tiempo de ejecución, seleccione una velocidad");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Velocidad seleccionada, presione iniciar");
        }
    }//GEN-LAST:event_btnDosActionPerformed

    private void btnTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTresActionPerformed
        btnUno.setSelected(false);
        btnDos.setSelected(false);
        btnCuatro.setSelected(false);
        if (ejecutando == true && btnTres.isSelected() == true) {
            p1.detener();
            p2.detener();
            p4.detener();
            p3.start();
        } else if (ejecutando == true && btnTres.isSelected() == false) {
            p3.detener();
            JOptionPane.showMessageDialog(rootPane, "desmarcó en tiempo de ejecución, seleccione una velocidad");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Velocidad seleccionada, presione iniciar");
        }
    }//GEN-LAST:event_btnTresActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        File[] files;
        p1 = new musicaTest(lblGaleria, btnUno, btnDos, btnTres, btnCuatro, btnIniciar, btnBocina);
        p2 = new serieDos(lblGaleria, btnUno, btnDos, btnTres, btnCuatro, btnIniciar, btnBocina);
        p3 = new serieTres(lblGaleria, btnUno, btnDos, btnTres, btnCuatro, btnIniciar, btnBocina);
        p4 = new serieCuatro(lblGaleria, btnUno, btnDos, btnTres, btnCuatro, btnIniciar, btnBocina);
        File file = new File("C:\\Users\\Gebel\\Desktop\\Sistemas\\topicos avanzados de prog\\galeriaHardcore\\src\\newpackage");
        JFileChooser chooser = new JFileChooser(file);
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setDialogTitle("Selecciona la secuencia para la película: ");
        chooser.showOpenDialog(rootPane);
        files = chooser.getSelectedFiles();
        int aux = files.length - 1;
        System.out.println(aux);
        auxiImg = new fileInstancia(files, aux);
        auxiIniciante = new fileInstancia(0);
        //ImageIcon im=new ImageIcon(new ImageIcon(files[1].getAbsolutePath()).getImage().getScaledInstance(WIDTH, HEIGHT, WIDTH));
        /////////////lblGaleria.setIcon(new ImageIcon(new ImageIcon(files[0].getAbsolutePath()).getImage().getScaledInstance(lblGaleria.getWidth(), lblGaleria.getHeight(), Image.SCALE_DEFAULT)));
        btnUno.setEnabled(true);
        btnUno.setSelected(true);
        btnDos.setEnabled(true);
        btnTres.setEnabled(true);
        btnCuatro.setEnabled(true);
        btnIniciar.setEnabled(true);
        btnBocina.setEnabled(true);
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        if (btnUno.isSelected()) {
            p1.start();
            btnIniciar.setEnabled(false);
            ejecutando = true;
        } else if (btnDos.isSelected()) {
            p2.start();
            btnIniciar.setEnabled(false);
            ejecutando = true;
        } else if (btnTres.isSelected()) {
            p3.start();
            btnIniciar.setEnabled(false);
            ejecutando = true;
        } else if (btnCuatro.isSelected()) {
            p4.start();
            btnIniciar.setEnabled(false);
            ejecutando = true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "no tiene ningun check marcado");
        }

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuatroActionPerformed
        btnUno.setSelected(false);
        btnDos.setSelected(false);
        btnTres.setSelected(false);
        if (ejecutando == true && btnCuatro.isSelected() == true) {
            p1.detener();
            p2.detener();
            p3.detener();
            p4.start();
        } else if (ejecutando == true && btnCuatro.isSelected() == false) {
            p4.detener();
            JOptionPane.showMessageDialog(rootPane, "desmarcó en tiempo de ejecución, seleccione una velocidad");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Velocidad seleccionada, presione iniciar");
        }
    }//GEN-LAST:event_btnCuatroActionPerformed

    private void btnBocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBocinaActionPerformed
        if (clip == null) {
            try {
                audioInputStream = AudioSystem.getAudioInputStream(new File("src/newpackage/cricri.wav").getAbsoluteFile());
                clip = AudioSystem.getClip();
                clip.open(audioInputStream); 
                clip.start();
                btnBocina.setText("⏸");
            } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
                Logger.getLogger(galeriaTAP.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            if (clip.isRunning()) {
                duracionPaus = clip.getFramePosition();
                clip.stop();
                btnBocina.setText("▶");
            } else {
                if (duracionPaus < clip.getFrameLength()) {
                    clip.setFramePosition((int) duracionPaus);
                } else {
                    clip.setFramePosition(0);
                }
                clip.start();
                btnBocina.setText("⏸");
            }
        }
    }//GEN-LAST:event_btnBocinaActionPerformed
    public static void stopMusic(){
        if (clip != null) {
            duracionPaus = 0;
            clip.stop();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(galeriaTAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(galeriaTAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(galeriaTAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(galeriaTAP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new galeriaTAP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBocina;
    private javax.swing.JRadioButton btnCuatro;
    private javax.swing.JRadioButton btnDos;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnLeer;
    private javax.swing.JRadioButton btnTres;
    private javax.swing.JRadioButton btnUno;
    private javax.swing.JLabel lblGaleria;
    // End of variables declaration//GEN-END:variables

}
